#! /bin/sh
#AUTOSTART
sxhkd -c ~/.config/sxhkd/sxhkdrc &
wal -Rq
picom &

#BAR
$HOME/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           12
bspc config focus_follow_pointer true
bspc config pointer_follow_focus false

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# pywal colors.
. "${HOME}/.cache/wal/colors.sh

# sets border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
